# Generated by Django 4.1.5 on 2023-01-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=100)),
                ('bill_type', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('congress', models.CharField(max_length=100)),
                ('chamber', models.CharField(max_length=100)),
                ('short_title', models.CharField(max_length=255)),
                ('sponsor_id', models.CharField(max_length=100)),
                ('sponsor_name', models.CharField(max_length=100)),
                ('sponsor_party', models.CharField(max_length=100)),
                ('sponsor_state', models.CharField(max_length=100)),
                ('sponsor_uri', models.CharField(max_length=255)),
                ('gpo_pdf_uri', models.CharField(max_length=255)),
                ('congressdotgov_url', models.CharField(max_length=255)),
                ('govtrack_url', models.CharField(max_length=255)),
                ('introduced_date', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('last_vote', models.CharField(max_length=100)),
                ('house_passage', models.CharField(max_length=100)),
                ('senate_passage', models.CharField(max_length=100)),
                ('enacted', models.CharField(max_length=100)),
                ('vetoed', models.CharField(max_length=100)),
                ('cosponsors', models.CharField(max_length=100)),
                ('committees', models.CharField(max_length=100)),
                ('primary_subject', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('summary_short', models.TextField()),
            ],
        ),
    ]
