# Generated by Django 4.1.5 on 2023-01-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('congress', models.CharField(max_length=10)),
                ('latest_action_date', models.DateField()),
                ('latest_action_text', models.TextField()),
                ('origin_chamber', models.CharField(max_length=10)),
                ('origin_chamber_code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('update_date', models.DateField()),
                ('url', models.URLField()),
                ('text_url', models.URLField(null=True)),
                ('summary', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioguide_id', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('party', models.CharField(max_length=255)),
                ('chamber', models.CharField(max_length=255)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('state', models.CharField(max_length=255)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillSponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bills')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.members')),
            ],
        ),
    ]
