# Generated by Django 4.1.5 on 2023-01-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='members',
            name='chamber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
