# Generated by Django 4.1.5 on 2023-02-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_members_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='img_url',
        ),
        migrations.AddField(
            model_name='members',
            name='img_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
